apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: picking
  description: O sistema de picking bla bla bla
  tags:
    - C#
    - mobile
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
    - url: https://github.com/cgrahl/yamls/blob/main/apis/picking-definition.yaml
      title: GitHub Repo
      icon: github
  annotations:
    backstage.io/techdocs-ref: https://guides.ambevdevs.com.br/pt-br/equipes/logco/TEC-LOG/Criar_Doc_Wiki
spec:
  type: service
  lifecycle: production
  owner: picking
  providesApis:
    - picking
