apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: picking
  # This is an extra long description
  description: O sistema de picking bla bla bla
  links:
    - url: https://github.com/cgrahl/yamls/blob/main/apis/picking-definition.yaml
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: picking
  providesApis:
    - picking
